#!/bin/bash
# run.sh

# Define distance metric and weight
# DISTANCE_METRIC="euclidean" # "euclidean" and "manhattan"
WEIGHT="uniform"  # "uniform" and "distance"

# Define the list of datasets
# DATASETS=("experimentA" "experimentB")
DATAPATH='./dataset/Arrhythmia_Data_Set'
SAVE_DIR="./trainlog"
k=5

# Define k start, end, and step
# K_START=3
# K_END=59
# K_STEP=2

# # Loop over datasets
# for DATASET in "${DATASETS[@]}"
# do
#     DATAPATH="./dataset/$DATASET"
#     echo "Running experiments for $DATASET"

#     # Loop over a range of k values generated by seq
#     for k in $(seq $K_START $K_STEP $K_END)
#     do
#         echo "Running experiment with k=$k"
#         python main.py --data_path $DATAPATH --k_value $k --distance_metric $DISTANCE_METRIC --weight $WEIGHT --save_dir $SAVE_DIR --k_start $K_START --k_end $K_END
#     done
# done


python main.py --data_path $DATAPATH --k_value $k --weight $WEIGHT --save_dir $SAVE_DIR 