#!/bin/bash
# run_RF.sh

# Define the list of datasets
DATASETS=("experimentA" "experimentB")
SAVE_DIR="./trainlog"

# Define k start, end, and step
n_START=10
n_END=50
n_STEP=1
MODEL="RF"

# Loop over datasets
for DATASET in "${DATASETS[@]}"
do
    DATAPATH="./dataset/$DATASET"
    echo "Running experiments for $DATASET"

    # Loop over a range of k values generated by seq
    for n_estimators in $(seq $n_START $n_STEP $n_END) 
    do
        echo "Running experiment with n_estimators=$n_estimators"
        python RF_main.py --data_path $DATAPATH --n_estimators $n_estimators --save_dir $SAVE_DIR --n_start $n_START --n_end $n_END --model $MODEL
    done
done
